import TreeNode from "./components/Files/FileService";

export const C_Tree = new TreeNode('C:', [

    new TreeNode('Games', [
        new TreeNode('APEX_Legends', [], 'Games', 'folder'),
        new TreeNode('Counter_Strike_2', [], 'Games', 'folder'),
        new TreeNode('Diablo_IV', [], 'Games', 'folder')
    ], 'C:', 'folder'),

    new TreeNode('Intel', [
        new TreeNode('system_files', [], 'Intel', 'folder'),
        new TreeNode('CPU_helper', [], 'Intel', 'folder'),
    ], 'C:', 'folder'),

    new TreeNode('PerfLogs', [
        new TreeNode('Some_System_file_1', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_2', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_3', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_4', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_5', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_6', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_7', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_8', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_9', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_10', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_11', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_12', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_13', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_14', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_15', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_16', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_17', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_18', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_19', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_20', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_21', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_22', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_23', [], 'PerfLogs', 'file'),
        new TreeNode('Some_System_file_24', [], 'PerfLogs', 'file'),
    ], 'C:', 'folder'),

    new TreeNode('Program_Files', [
        new TreeNode('Some_Program_file_1', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_2', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_3', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_4', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_5', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_6', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_7', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_8', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_9', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_10', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_11', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_12', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_13', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_14', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_15', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_16', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_17', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_18', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_19', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_20', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_21', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_22', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_23', [], 'Program_Files', 'file'),
        new TreeNode('Some_Program_file_24', [], 'Program_Files', 'file'),
    ], 'C:', 'folder'),

    new TreeNode('Program_Files(x86)', [
        new TreeNode('Some_Program_file_1(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_2(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_3(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_4(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_5(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_6(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_7(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_8(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_9(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_10(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_11(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_12(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_13(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_14(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_15(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_16(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_17(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_18(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_19(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_20(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_21(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_22(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_23(x86)', [], 'Program_Files(x86)', 'file'),
        new TreeNode('Some_Program_file_24(x86)', [], 'Program_Files(x86)', 'file'),
    ], 'C:', 'folder'),

    new TreeNode('Windows_XP', [
        new TreeNode('WIN_1', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_2', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_3', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_4', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_5', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_6', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_7', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_8', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_9', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_10', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_11', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_12', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_13', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_14', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_15', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_16', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_17', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_18', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_19', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_20', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_21', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_22', [], 'Windows_XP', 'file'),
        new TreeNode('WIN_23', [], 'Windows_XP', 'file'),
        new TreeNode('virus.troyan', [], 'Windows_XP', 'file'),
    ], 'C:', 'folder'),

    new TreeNode('Users', [
        new  TreeNode('YourUser', [], 'Users', 'file'),
        new  TreeNode('NotYourUser', [], 'Users', 'file'),
    ], 'C:', 'folder'),
])